#!/usr/bin/env sh

REPO_URL="https://github.com/ndbaker1/conf.git"

[ -d $HOME/.dotfiles.git ] || $(
  git clone --bare $REPO_URL $HOME/.dotfiles.git && \
  dotfiles checkout && \
  dotfiles config --local status.showUntrackedFiles no
)

git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME $@
