#!/bin/sh
# Grab base dotfiles
yes Y | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ndbaker1/dotfiles/main/.local/bin/dot)"

# Neovim Appimage installation for cross compatibility
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
./nvim.appimage

